// /**
//  * Handles request validation errors generated by
//  * express-validator.
//  */
//     const errors = validationResult(req);

//     if (!errors.isEmpty()) {
//         throw new ApiError(
//             400,
//             errors
//                 .array()
//                 .map((error) => error.msg)
//                 .join(" ")
//         );
//     }

//     next();
// }


import { validationResult } from "express-validator";
import { ApiError } from "../utils/ApiError.js";

/**
 * Handles request validation errors generated by
 * express-validator.
 */
export function validationMiddleware(req, res, next) {
    const errors = validationResult(req);

    if (!errors.isEmpty()) {
        const message = errors
            .array()
            .map((error) => error.msg)
            .join(" ");

        throw new ApiError(400, message);
    }

    next();
}
