import { validationResult } from "express-validator";

import { ApiError } from "../utils/ApiError.js";

/**
 * Handles request validation errors generated by
 * express-validator.
 */
export function validationMiddleware(req, res, next) {
    const errors = validationResult(req);

    if (!errors.isEmpty()) {
        throw new ApiError(
            400,
            errors
                .array()
                .map((error) => errors.msg)
                .join(" ")
        );
    }

    next();
}