import { validationResult } from "express-validator";

/**
 * Returns validation errors generated by express-validator
 * in a consistent API response format.
 *
 * This middleware must run after the route validators.
 */
export const validateRequest = (req, res, next) => {
    const errors = validationResult(req);

    if (!errors.isEmpty()) {
        return res.status(400).json({
            success: false,
            message: "Validation failed.",
            errors: errors.array()
        });
    }

    next();
};