import { body } from "express-validator";

/**
 * Validates login credentials before they reach the authentication
 * service.
 *
 * Keeping request validation separate from authentication business
 * logic ensures the service can focus on authentication rules rather
 * than malformed HTTP input.
 */
export const loginValidator = [
    body("identifier")
        .trim()
        .notEmpty()
        .withMessage("Username or email is required."),

    body("password")
        .isString()
        .notEmpty()
        .withMessage("Password is required.")
];

/**
 * Validates the refresh-token request before it reaches the
 * authentication service.
 *
 * The refresh token is treated as a string because it is a JWT
 * credential generated by the authentication service.
 */
export const refreshTokenValidator = [
    body("refreshToken")
        .isString()
        .withMessage("Refresh token must be a string.")
        .trim()
        .notEmpty()
        .withMessage("Refresh token is required.")
];